<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TODOCommon\**" />
    <Compile Remove="TODODataService\**" />
    <Compile Remove="TODOTransactionServices\**" />
    <EmbeddedResource Remove="TODOCommon\**" />
    <EmbeddedResource Remove="TODODataService\**" />
    <EmbeddedResource Remove="TODOTransactionServices\**" />
    <None Remove="TODOCommon\**" />
    <None Remove="TODODataService\**" />
    <None Remove="TODOTransactionServices\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TODOCommon\TODOCommon.csproj" />
    <ProjectReference Include="..\TODOTransactionServices\TODOTransactionServices.csproj" />
  </ItemGroup>

</Project>
